version: '3.8'

services:
  # Watchtower for automated container updates
  watchtower:
    image: containrrr/watchtower:latest
    container_name: n8n-watchtower
    restart: unless-stopped
    environment:
      # Update check interval (default: 24 hours)
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL:-86400}
      # Only update containers with this label
      - WATCHTOWER_LABEL_ENABLE=${WATCHTOWER_LABEL_ENABLE:-true}
      # Cleanup old images after update
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP:-true}
      # Include stopped containers
      - WATCHTOWER_INCLUDE_STOPPED=${WATCHTOWER_INCLUDE_STOPPED:-true}
      # Remove old images after update
      - WATCHTOWER_REMOVE_VOLUMES=${WATCHTOWER_REMOVE_VOLUMES:-false}
      # Update schedule (cron format) - default: daily at 2 AM
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE:-0 0 2 * * *}
      # Notification settings
      - WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS:-slack}
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${SLACK_WEBHOOK_URL}
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=${WATCHTOWER_SLACK_IDENTIFIER:-n8n-autoupdate}
      - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=${WATCHTOWER_SLACK_CHANNEL:-#alerts}
      # Email notifications (optional)
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER_EMAIL_FROM}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL_TO}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${WATCHTOWER_EMAIL_SERVER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${WATCHTOWER_EMAIL_PORT:-587}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER_EMAIL_USER}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER_EMAIL_PASSWORD}
      # Debug mode
      - WATCHTOWER_DEBUG=${WATCHTOWER_DEBUG:-false}
      # Rolling restart (update one container at a time)
      - WATCHTOWER_ROLLING_RESTART=${WATCHTOWER_ROLLING_RESTART:-true}
      # Timeout for container stop (seconds)
      - WATCHTOWER_TIMEOUT=${WATCHTOWER_TIMEOUT:-10s}
      # Run once and exit (for manual updates)
      - WATCHTOWER_RUN_ONCE=${WATCHTOWER_RUN_ONCE:-false}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs/watchtower:/logs
    networks:
      - n8n-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    command: >
      --label-enable
      --cleanup
      --include-stopped
      --rolling-restart
      --notifications-level info
      --notification-template-title="N8N Update: {{.Project}}"
      --notification-template-body="Container {{.Container}} updated from {{.OldImage}} to {{.NewImage}}"
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -v grep | grep watchtower || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  n8n-network:
    external: true

volumes:
  watchtower-logs:
    driver: local
