# Docker Compose version is now optional and deprecated

services:
  # Watchtower for automated container updates
  watchtower:
    image: containrrr/watchtower:v1.7.1
    container_name: n8n-watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL:-86400}
      - WATCHTOWER_LABEL_ENABLE=${WATCHTOWER_LABEL_ENABLE:-true}
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP:-true}
      - WATCHTOWER_INCLUDE_STOPPED=${WATCHTOWER_INCLUDE_STOPPED:-true}
      - WATCHTOWER_REMOVE_VOLUMES=${WATCHTOWER_REMOVE_VOLUMES:-false}
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE:-0 0 2 * * *}
      - WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS:-}
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${SLACK_WEBHOOK_URL:-}
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=${WATCHTOWER_SLACK_IDENTIFIER:-n8n-autoupdate}
      - WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=${WATCHTOWER_SLACK_CHANNEL:-alerts}
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${WATCHTOWER_EMAIL_FROM:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL_TO:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${WATCHTOWER_EMAIL_SERVER:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${WATCHTOWER_EMAIL_PORT:-587}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${WATCHTOWER_EMAIL_USER:-}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${WATCHTOWER_EMAIL_PASSWORD:-}
      - WATCHTOWER_DEBUG=${WATCHTOWER_DEBUG:-false}
      - WATCHTOWER_ROLLING_RESTART=${WATCHTOWER_ROLLING_RESTART:-true}
      - WATCHTOWER_TIMEOUT=${WATCHTOWER_TIMEOUT:-10s}
      - WATCHTOWER_RUN_ONCE=${WATCHTOWER_RUN_ONCE:-false}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs/watchtower:/logs
    networks:
      - n8n-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    command: >
      --label-enable
      --cleanup
      --include-stopped
      --rolling-restart
      --notifications-level info
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -v grep | grep watchtower || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  n8n-network:
    external: true

volumes:
  watchtower-logs:
    driver: local
