# Dynamic Middleware Configuration
http:
  middlewares:
    # Security headers middleware
    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
          - PATCH
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 100
        addVaryHeader: true
        referrerPolicy: "same-origin"
        customFrameOptionsValue: "DENY"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    # Rate limiting middleware
    rate-limit:
      rateLimit:
        burst: 100
        average: 50

    # API rate limiting (more restrictive)
    api-rate-limit:
      rateLimit:
        burst: 20
        average: 10

    # Basic auth middleware (for admin endpoints)
    basic-auth:
      basicAuth:
        users:
          - "admin:$2y$10$K8QJZz.ZJZ5Z5Z5Z5Z5Z5O"  # admin:admin (change this!)

    # IP whitelist for admin access (optional)
    # admin-whitelist:
    #   ipWhiteList:
    #     sourceRange:
    #       - "127.0.0.1/32"
    #       - "192.168.1.0/24"
    #       - "10.0.0.0/8"

    # Compress responses
    compress:
      compress: {}

    # CORS middleware for webhooks
    cors:
      headers:
        accessControlAllowCredentials: true
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-Requested-With"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 86400
