# Prometheus Alert Rules for N8N-R8

groups:
  - name: n8n-r8-alerts
    rules:
      # Service availability alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on instance {{ $labels.instance }} has been down for more than 1 minute."

      - alert: N8NDown
        expr: up{job="n8n"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "N8N service is down"
          description: "N8N service has been down for more than 30 seconds."

      - alert: N8NExtendedDowntime
        expr: up{job="n8n"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "N8N extended downtime detected"
          description: "N8N service has been down for more than 5 minutes. Immediate investigation required."

      # System resource alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}."

      - alert: CriticalCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 95
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Critical CPU usage detected"
          description: "CPU usage is above 95% for more than 2 minutes on {{ $labels.instance }}."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 5 minutes on {{ $labels.instance }}."

      - alert: CriticalMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 95
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Critical memory usage detected"
          description: "Memory usage is above 95% for more than 2 minutes on {{ $labels.instance }}."

      # Disk space alerts
      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is above 80% on {{ $labels.mountpoint }} for {{ $labels.instance }}."

      - alert: CriticalDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100 > 90
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Critical disk usage detected"
          description: "Disk usage is above 90% on {{ $labels.mountpoint }} for {{ $labels.instance }}."

      - alert: DiskFull
        expr: (node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100 > 95
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Disk almost full"
          description: "Disk usage is above 95% on {{ $labels.mountpoint }} for {{ $labels.instance }}. Immediate action required."

      # Container-specific alerts
      - alert: ContainerHighCPU
        expr: rate(container_cpu_usage_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container high CPU usage"
          description: "Container {{ $labels.name }} is using more than 80% CPU for 5 minutes."

      - alert: ContainerHighMemory
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container high memory usage"
          description: "Container {{ $labels.name }} is using more than 90% of its memory limit."

      - alert: ContainerRestarting
        expr: rate(container_last_seen[5m]) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Container restarting frequently"
          description: "Container {{ $labels.name }} has been restarting frequently."

      # N8N specific alerts
      - alert: N8NHighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="n8n"}[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "N8N high response time"
          description: "N8N 95th percentile response time is above 2 seconds for 5 minutes."

      - alert: N8NHighErrorRate
        expr: rate(http_requests_total{job="n8n",status=~"5.."}[5m]) / rate(http_requests_total{job="n8n"}[5m]) * 100 > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "N8N high error rate"
          description: "N8N error rate is above 5% for 5 minutes."

      # Database alerts
      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been down for more than 1 minute."

      - alert: PostgreSQLTooManyConnections
        expr: pg_stat_activity_count > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL too many connections"
          description: "PostgreSQL has more than 80 active connections."

      # Redis alerts
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis cache has been down for more than 1 minute."

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis high memory usage"
          description: "Redis is using more than 90% of its allocated memory."

      # Network and connectivity alerts
      - alert: HighNetworkTraffic
        expr: rate(node_network_receive_bytes_total[5m]) + rate(node_network_transmit_bytes_total[5m]) > 100000000  # 100MB/s
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High network traffic"
          description: "Network traffic is above 100MB/s for 5 minutes on {{ $labels.instance }}."

      - alert: HTTPEndpointDown
        expr: probe_success == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "HTTP endpoint down"
          description: "HTTP endpoint {{ $labels.instance }} has been down for more than 2 minutes."

      # Backup and maintenance alerts
      - alert: BackupFailed
        expr: time() - backup_last_success_timestamp > 86400  # 24 hours
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Backup has not run successfully"
          description: "Backup has not completed successfully in the last 24 hours."

      - alert: LogVolumeHigh
        expr: rate(log_entries_total[5m]) > 1000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High log volume"
          description: "Log entry rate is above 1000 entries per second for 10 minutes."

  - name: n8n-r8-maintenance
    rules:
      # Predictive alerts
      - alert: DiskWillFillIn4Hours
        expr: predict_linear(node_filesystem_free_bytes[1h], 4*3600) < 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Disk will fill in 4 hours"
          description: "Based on current usage, disk {{ $labels.mountpoint }} on {{ $labels.instance }} will fill in approximately 4 hours."

      - alert: MemoryLeakDetected
        expr: increase(container_memory_usage_bytes[1h]) > 100000000  # 100MB increase per hour
        for: 2h
        labels:
          severity: warning
        annotations:
          summary: "Potential memory leak detected"
          description: "Container {{ $labels.name }} memory usage has increased by more than 100MB per hour for 2 hours."
