name: Shell Script Validation

on:
  push:
    paths:
      - "**.sh"
  pull_request:
    paths:
      - "**.sh"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install shellcheck
        run: |
          if command -v sudo >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y shellcheck
          else
            apt-get update
            apt-get install -y shellcheck
          fi

      - name: Run shellcheck
        run: |
          find . -type f -name "*.sh" \
            -not -path "./node_modules/*" \
            -not -path "./nodes/node_modules/*" \
            -not -path "./data/*" \
            -not -path "./.git/*" \
            -not -path "./logs/*" \
            -exec shellcheck {} \;
